export type Language = 'pt' | 'fr' | 'en';

export type LocalizedText = Record<Language, string>;

export type MenuItem = {
  name: string;
  detail: LocalizedText;
  marker: string;
  group?: LocalizedText;
};

export type MenuGroup = 'pizzas' | 'entradas' | 'doces';

const text = (pt: string, fr: string, en: string): LocalizedText => ({ pt, fr, en });

export const menuGroups: Record<MenuGroup, MenuItem[]> = {
  pizzas: [
    {
      name: 'Marina',
      detail: text(
        'Molho de tomate San Marzano DOP, tomate-cereja confitado, azeitonas, orégãos selvagens, alho, manjericão fresco e azeite virgem extra',
        'Sauce tomate San Marzano DOP, tomates cerises confites, olives, origan sauvage, ail, basilic frais et huile d’olive extra vierge',
        'San Marzano DOP tomato sauce, confit cherry tomatoes, olives, wild oregano, garlic, fresh basil and extra virgin olive oil',
      ),
      marker: 'glu',
      group: text('Pizzas Clássicas', 'Pizzas Classiques', 'Classic Pizzas'),
    },
    {
      name: 'Margherita',
      detail: text(
        'Molho de tomate San Marzano DOP, Fior di Latte, Parmigiano Reggiano DOP, manjericão fresco e azeite virgem extra',
        'Sauce tomate San Marzano DOP, Fior di Latte, Parmigiano Reggiano DOP, basilic frais et huile d’olive extra vierge',
        'San Marzano DOP tomato sauce, Fior di Latte, Parmigiano Reggiano DOP, fresh basil and extra virgin olive oil',
      ),
      marker: 'glu · lei',
    },
    {
      name: 'Little Italy',
      detail: text(
        'Pesto Genovês, Fior di Latte, tomate-cereja confitado, Stracciatella, manjericão fresco e lascas de Parmigiano Reggiano DOP',
        'Pesto génois, Fior di Latte, tomates cerises confites, Stracciatella, basilic frais et copeaux de Parmigiano Reggiano DOP',
        'Genovese pesto, Fior di Latte, confit cherry tomatoes, Stracciatella, fresh basil and Parmigiano Reggiano DOP shavings',
      ),
      marker: 'glu · lei · frc',
    },
    {
      name: 'Queen',
      detail: text(
        'Molho de tomate San Marzano DOP, Fior di Latte, Prosciutto Cotto, cogumelos, azeitonas e orégãos',
        'Sauce tomate San Marzano DOP, Fior di Latte, Prosciutto Cotto, champignons, olives et origan',
        'San Marzano DOP tomato sauce, Fior di Latte, Prosciutto Cotto, mushrooms, olives and oregano',
      ),
      marker: 'glu · lei',
    },
    {
      name: 'Menage à 4',
      detail: text(
        'Base de natas, Fior di Latte, Gorgonzola Dolce, Provola Affumicata, Taleggio, manjericão fresco e um toque de mel',
        'Base crème, Fior di Latte, Gorgonzola Dolce, Provola Affumicata, Taleggio, basilic frais et une touche de miel',
        'Cream base, Fior di Latte, Gorgonzola Dolce, Provola Affumicata, Taleggio, fresh basil and a touch of honey',
      ),
      marker: 'glu · lei',
    },
    {
      name: 'Oriental',
      detail: text(
        'Molho de tomate San Marzano DOP, Fior di Latte, Merguez, cebola grelhada, ovo, azeitonas e maionese de ras el hanout',
        'Sauce tomate San Marzano DOP, Fior di Latte, merguez, oignon grillé, œuf, olives et mayonnaise au ras el-hanout',
        'San Marzano DOP tomato sauce, Fior di Latte, merguez, grilled onion, egg, olives and ras el hanout mayonnaise',
      ),
      marker: 'glu · lei · ovo',
    },
    {
      name: 'Tuna Club',
      detail: text(
        'Fior di Latte, tomate amarelo, cebola grelhada, atum, azeitona, cebolinha e pickles',
        'Fior di Latte, tomate jaune, oignon grillé, thon, olives, ciboulette et pickles',
        'Fior di Latte, yellow tomato, grilled onion, tuna, olives, chives and pickles',
      ),
      marker: 'glu · lei · pei',
    },
    {
      name: 'Hot Honey Lover',
      detail: text(
        'Creme de pimentos assados, Fior di Latte, salame picante, malagueta, mel picante, raspas de lima e manjericão fresco',
        'Crème de poivrons rôtis, Fior di Latte, salami piquant, piment, miel épicé, zeste de citron vert et basilic frais',
        'Roasted pepper cream, Fior di Latte, spicy salami, chilli, hot honey, lime zest and fresh basil',
      ),
      marker: 'glu · lei',
      group: text('Pizzas de Assinatura', 'Pizzas Signature', 'Signature Pizzas'),
    },
    {
      name: 'Esmeralda',
      detail: text(
        'Fior di Latte, Mortadella Bologna IGP «Massima», Stracciatella, pesto de pistácio com Pecorino, pistácios torrados e manjericão fresco',
        'Fior di Latte, Mortadella Bologna IGP «Massima», Stracciatella, pesto de pistache au Pecorino, pistaches torréfiées et basilic frais',
        'Fior di Latte, Mortadella Bologna IGP “Massima”, Stracciatella, pistachio and Pecorino pesto, toasted pistachios and fresh basil',
      ),
      marker: 'glu · lei · frc',
    },
    {
      name: 'Aleluia',
      detail: text(
        'Molho de tomate San Marzano DOP, Fior di Latte, Gorgonzola Dolce, Prosciutto di Parma, figos, manjericão fresco e lascas de Parmigiano Reggiano DOP',
        'Sauce tomate San Marzano DOP, Fior di Latte, Gorgonzola Dolce, Prosciutto di Parma, figues, basilic frais et copeaux de Parmigiano Reggiano DOP',
        'San Marzano DOP tomato sauce, Fior di Latte, Gorgonzola Dolce, Prosciutto di Parma, figs, fresh basil and Parmigiano Reggiano DOP shavings',
      ),
      marker: 'glu · lei',
    },
    {
      name: 'Smoked Calzone',
      detail: text(
        'Molho de tomate San Marzano DOP, Provola Affumicata, Prosciutto Cotto, ovo de baixa temperatura, cogumelos, nata e azeite extra virgem',
        'Sauce tomate San Marzano DOP, Provola Affumicata, Prosciutto Cotto, œuf basse température, champignons, crème et huile d’olive extra vierge',
        'San Marzano DOP tomato sauce, Provola Affumicata, Prosciutto Cotto, slow-cooked egg, mushrooms, cream and extra virgin olive oil',
      ),
      marker: 'glu · lei · ovo',
    },
    {
      name: 'Truff Me Baby',
      detail: text(
        'Creme de trufa, Fior di Latte, Gorgonzola Dolce, avelãs torradas com trufa, rúcula e mel',
        'Crème de truffe, Fior di Latte, Gorgonzola Dolce, noisettes torréfiées à la truffe, roquette et miel',
        'Truffle cream, Fior di Latte, Gorgonzola Dolce, truffle-toasted hazelnuts, rocket and honey',
      ),
      marker: 'glu · lei · frc',
    },
    {
      name: 'La Polpetta',
      detail: text(
        'Molho de tomate San Marzano DOP, Provola Affumicata, grelos de nabo, almôndega, tomate amarelo, pecorino e azeitonas',
        'Sauce tomate San Marzano DOP, Provola Affumicata, fanes de navet, boulette de viande, tomate jaune, pecorino et olives',
        'San Marzano DOP tomato sauce, Provola Affumicata, turnip greens, meatball, yellow tomato, pecorino and olives',
      ),
      marker: 'glu · lei',
    },
    {
      name: 'Truffle Obsession',
      detail: text(
        'Creme de trufa, Fior di Latte, Prosciutto di Parma, Stracciatella, avelãs torradas com trufa, carpaccio de trufa, azeite de trufa branca e rúcula',
        'Crème de truffe, Fior di Latte, Prosciutto di Parma, Stracciatella, noisettes torréfiées à la truffe, carpaccio de truffe, huile de truffe blanche et roquette',
        'Truffle cream, Fior di Latte, Prosciutto di Parma, Stracciatella, truffle-toasted hazelnuts, truffle carpaccio, white truffle oil and rocket',
      ),
      marker: 'glu · lei · frc',
    },
    {
      name: 'Pizza da Gigi',
      detail: text(
        'Passata rústica de tomate datterino amarelo, Fior di Latte, Presunto de Parma DOP curado 24 meses, burrata, rúcula, creme balsâmico e flores comestíveis',
        'Passata rustique de tomate datterino jaune, Fior di Latte, jambon de Parme DOP affiné 24 mois, burrata, roquette, crème balsamique et fleurs comestibles',
        'Rustic yellow datterino tomato passata, Fior di Latte, 24-month Parma ham DOP, burrata, rocket, balsamic glaze and edible flowers',
      ),
      marker: 'glu · lei',
    },
  ],
  entradas: [
    {
      name: 'Salame Finocchiona',
      detail: text('Salame Finocchiona italiano, servido com pickles artesanais', 'Salame Finocchiona italien, servi avec des pickles maison', 'Italian Finocchiona salami served with house-made pickles'),
      marker: '',
    },
    {
      name: 'Pão de Alho',
      detail: text('Pão de alho com manteiga artesanal de alho, salsa e pó de amêndoa', 'Pain à l’ail, beurre maison à l’ail, persil et poudre d’amande', 'Garlic bread with house-made garlic butter, parsley and almond powder'),
      marker: 'glu · lei · frc',
    },
    {
      name: 'Stracciatella Trufada',
      detail: text('Stracciatella fumada com trufa, servida com tiras de massa de pizza artesanal', 'Stracciatella fumée à la truffe, servie avec des bandes de pâte à pizza artisanale', 'Smoked truffle Stracciatella served with strips of house-made pizza dough'),
      marker: 'glu · lei',
    },
    {
      name: 'Tomates & Búfala',
      detail: text('Tomates assados no forno, mozzarella de búfala cremosa, servidos com tiras de massa de pizza artesanal', 'Tomates rôties au four, mozzarella di bufala crémeuse et bandes de pâte à pizza artisanale', 'Oven-roasted tomatoes, creamy buffalo mozzarella and strips of house-made pizza dough'),
      marker: 'glu · lei',
    },
    {
      name: 'Carpaccio de Novilho',
      detail: text('Carpaccio de novilho do Mercado de Alvalade, pesto de pistácio e pecorino, Parmigiano Reggiano DOP, ervas frescas e azeite virgem extra', 'Carpaccio de bœuf du Mercado de Alvalade, pesto de pistache et pecorino, Parmigiano Reggiano DOP, herbes fraîches et huile d’olive extra vierge', 'Beef carpaccio from Mercado de Alvalade, pistachio and pecorino pesto, Parmigiano Reggiano DOP, fresh herbs and extra virgin olive oil'),
      marker: 'lei · frc',
    },
    {
      name: 'Carpaccio de Gambão Vermelho',
      detail: text('Carpaccio de gambão vermelho com azeite virgem extra, raspas de citrinos, flor de sal, malagueta e manjericão fresco', 'Carpaccio de crevette rouge, huile d’olive extra vierge, zestes d’agrumes, fleur de sel, piment et basilic frais', 'Red prawn carpaccio with extra virgin olive oil, citrus zest, sea salt, chilli and fresh basil'),
      marker: 'cru',
    },
  ],
  doces: [
    { name: 'Tiramisù Clássico', detail: text('', '', ''), marker: 'glu · lei · ovo' },
    { name: 'Tiramisù Biscoff', detail: text('', '', ''), marker: 'glu · lei · ovo' },
    {
      name: 'Panuzzo de Pistácio',
      detail: text('Massa de pizza, creme de pistácio, pistácios crocantes e açúcar em pó', 'Pâte à pizza, crème de pistache, pistaches croquantes et sucre glace', 'Pizza dough, pistachio cream, crunchy pistachios and icing sugar'),
      marker: 'glu · lei · frc',
    },
    {
      name: 'Panuzzo de Nutella',
      detail: text('Massa de pizza, Nutella, avelãs crocantes e açúcar em pó', 'Pâte à pizza, Nutella, noisettes croquantes et sucre glace', 'Pizza dough, Nutella, crunchy hazelnuts and icing sugar'),
      marker: 'glu · lei · frc',
    },
  ],
};

export const ui = {
  pt: {
    language: 'Idioma',
    nav: ['Menu', 'A nossa história', 'Visita-nos', 'Contactos'],
    reserve: 'Liga-nos',
    mobileOpen: 'Abrir menu',
    mobileClose: 'Fechar menu',
    ticker: 'TER — QUI · 18H — 22H · SEX — SÁB · 12H — 22H',
    heroEyebrow: 'Napoli encontra Alvalade',
    heroTitle: 'Uma boa pizza',
    heroEmphasis: 'faz-se notar.',
    heroIntro: 'Massa leve, fermentação lenta e aquele tipo de mesa onde se fica mais um bocadinho. França no nome, Portugal no coração e Nápoles na massa.',
    viewMenu: 'Ver o menu',
    visitUs: 'Vem ter connosco',
    heroCaption: 'pizza, sem cerimónia',
    sideNote: 'entra, escolhe, repete',
    marquee: 'Se for pra ter problemas, que sejam para escolher o sabor',
    menuEyebrow: 'A nossa carta',
    menuTitle: 'Escolhe o teu',
    menuEmphasis: 'problema.',
    menuAside: 'Tudo começa numa massa de fermentação lenta, aberta à mão todos os dias.',
    menuTabs: ['Pizzas', 'Para começar', 'Final feliz', 'Bebidas'],
    menuNote: 'feito à mão · todos os dias',
    allergy: 'glu — glúten · lei — leite · frc — frutos de casca rija · pei — peixe · cru — crustáceos · ovo — ovo · sul — sulfitos',
    drinksEyebrow: 'Para acompanhar',
    drinksTitle: 'Molho, bolhas',
    drinksEmphasis: 'e boa conversa.',
    drinksBody: 'Há vinho natural no copo, cerveja bem fresca e cocktails que não levam demasiado a sério o aperitivo italiano.',
    askList: 'Pergunta pela carta',
    drinkOne: 'Spritz da casa',
    drinkOneDetail: 'laranja · bitter · prosecco',
    drinkTwo: 'Vinho tinto',
    drinkTwoDetail: 'leve, fresco, sem pose',
    storyEyebrow: 'A nossa história',
    storyTitle: 'O nome é francês.',
    storyEmphasis: 'A vontade é daqui.',
    storyBodyOne: 'Kevin trouxe mais de 12 anos de pizza e cozinha de Paris para Lisboa. Com Giselle, criou um lugar de bairro feito para clientes habituais e mesas demoradas.',
    storyBodyTwo: 'Ao lado do Mercado de Alvalade, juntamos massa de fermentação lenta com ingredientes italianos e portugueses.',
    directions: 'Conhece o caminho',
    storyQuote: 'Uma pizzaria de bairro, uma comunidade à volta da pizza.',
    visitEyebrow: 'Vem visitar-nos',
    visitTitle: 'Mesmo ao lado',
    visitEmphasis: 'do Mercado.',
    visitLede: 'No centro do bairro. Traz amigos, traz apetite e traz o teu patudo — somos pet friendly.',
    hoursLabel: 'Horário',
    daysOne: 'Terça a quinta',
    daysTwo: 'Sexta e sábado',
    daysClosed: 'Domingo e segunda',
    closed: 'fechado',
    hoursNote: 'Mesas por ordem de chegada. Somos pet friendly.',
    location: 'Onde estamos',
    openDirections: 'Abrir direções',
    socialEyebrow: 'Da nossa mesa',
    socialTitle: 'Vemo-nos no',
    socialEmphasis: 'Instagram.',
    viewMore: 'ver mais',
    socialQuote: 'O teu coração não é de pedra.',
    socialQuoteSmall: 'É de mozzarella e derrete fácil.',
    footerTagline: 'Um pizza bar com sotaque de Alvalade.',
    contact: 'Fala connosco',
    comeBy: 'Passa por cá',
    footerMade: 'feito com fome em Lisboa',
    backTop: 'Voltar ao topo',
  },
  fr: {
    language: 'Langue',
    nav: ['Menu', 'Notre histoire', 'Nous trouver', 'Contacts'],
    reserve: 'Appelez-nous',
    mobileOpen: 'Ouvrir le menu',
    mobileClose: 'Fermer le menu',
    ticker: 'MAR — JEU · 18H — 22H · VEN — SAM · 12H — 22H',
    heroEyebrow: 'Naples rencontre Alvalade',
    heroTitle: 'Une bonne pizza',
    heroEmphasis: 'ne passe pas inaperçue.',
    heroIntro: 'Une pâte légère, une fermentation lente et une table où l’on reste encore un peu. La France dans le nom, le Portugal dans le cœur et Naples dans la pâte.',
    viewMenu: 'Voir le menu',
    visitUs: 'Venez nous voir',
    heroCaption: 'pizza, sans cérémonie',
    sideNote: 'entrez, choisissez, recommencez',
    marquee: 'S’il faut avoir un problème, que ce soit de choisir la pizza',
    menuEyebrow: 'Notre carte',
    menuTitle: 'Choisissez votre',
    menuEmphasis: 'problème.',
    menuAside: 'Tout commence par une pâte à fermentation lente, façonnée à la main chaque jour.',
    menuTabs: ['Pizzas', 'Pour commencer', 'Final sucré', 'Boissons'],
    menuNote: 'fait main · tous les jours',
    allergy: 'glu — gluten · lei — lait · frc — fruits à coque · pei — poisson · cru — crustacés · ovo — œuf · sul — sulfites',
    drinksEyebrow: 'Pour accompagner',
    drinksTitle: 'Sauce, bulles',
    drinksEmphasis: 'et conversation.',
    drinksBody: 'Du vin naturel au verre, de la bière bien fraîche et des cocktails qui ne prennent pas trop au sérieux l’apéritif italien.',
    askList: 'Demander la carte',
    drinkOne: 'Spritz maison',
    drinkOneDetail: 'orange · bitter · prosecco',
    drinkTwo: 'Vin rouge',
    drinkTwoDetail: 'léger, frais, sans pose',
    storyEyebrow: 'Notre histoire',
    storyTitle: 'Le nom est français.',
    storyEmphasis: 'L’envie est d’ici.',
    storyBodyOne: 'Kevin a apporté de Paris à Lisbonne plus de 12 ans de pizza et de cuisine. Avec Giselle, il a créé une adresse de quartier pour les habitués et les longues tablées.',
    storyBodyTwo: 'À côté du Mercado de Alvalade, nous réunissons une pâte à fermentation lente et des produits italiens et portugais.',
    directions: 'Voir le chemin',
    storyQuote: 'Une pizzeria de quartier, une communauté autour de la pizza.',
    visitEyebrow: 'Venez nous voir',
    visitTitle: 'Juste à côté',
    visitEmphasis: 'du Mercado.',
    visitLede: 'Au cœur du quartier. Venez avec vos amis, votre appétit et votre compagnon à quatre pattes — nous sommes pet friendly.',
    hoursLabel: 'Horaires',
    daysOne: 'Mardi à jeudi',
    daysTwo: 'Vendredi et samedi',
    daysClosed: 'Dimanche et lundi',
    closed: 'fermé',
    hoursNote: 'Tables par ordre d’arrivée. Nous sommes pet friendly.',
    location: 'Où nous trouver',
    openDirections: 'Ouvrir l’itinéraire',
    socialEyebrow: 'Depuis notre table',
    socialTitle: 'Retrouvez-nous sur',
    socialEmphasis: 'Instagram.',
    viewMore: 'voir plus',
    socialQuote: 'Votre cœur n’est pas de pierre.',
    socialQuoteSmall: 'Il est en mozzarella et fond facilement.',
    footerTagline: 'Un pizza bar avec l’accent d’Alvalade.',
    contact: 'Nous contacter',
    comeBy: 'Passez nous voir',
    footerMade: 'fait avec appétit à Lisbonne',
    backTop: 'Retour en haut',
  },
  en: {
    language: 'Language',
    nav: ['Menu', 'Our story', 'Visit us', 'Contacts'],
    reserve: 'Call us',
    mobileOpen: 'Open menu',
    mobileClose: 'Close menu',
    ticker: 'TUE — THU · 6PM — 10PM · FRI — SAT · 12PM — 10PM',
    heroEyebrow: 'Naples meets Alvalade',
    heroTitle: 'A good pizza',
    heroEmphasis: 'gets noticed.',
    heroIntro: 'Light dough, slow fermentation and the kind of table where you stay a little longer. France in the name, Portugal in the heart and Naples in the dough.',
    viewMenu: 'View the menu',
    visitUs: 'Come and see us',
    heroCaption: 'pizza, no ceremony',
    sideNote: 'come in, choose, repeat',
    marquee: 'If you must have a problem, let it be choosing your pizza',
    menuEyebrow: 'Our menu',
    menuTitle: 'Choose your',
    menuEmphasis: 'problem.',
    menuAside: 'It all starts with slow-fermented dough, shaped by hand every day.',
    menuTabs: ['Pizzas', 'To start', 'Sweet finish', 'Drinks'],
    menuNote: 'made by hand · every day',
    allergy: 'glu — gluten · lei — milk · frc — tree nuts · pei — fish · cru — shellfish · ovo — egg · sul — sulphites',
    drinksEyebrow: 'To go with it',
    drinksTitle: 'Sauce, bubbles',
    drinksEmphasis: 'and good talk.',
    drinksBody: 'Natural wine by the glass, cold beer and cocktails that do not take the Italian aperitivo too seriously.',
    askList: 'Ask for the drinks list',
    drinkOne: 'House Spritz',
    drinkOneDetail: 'orange · bitter · prosecco',
    drinkTwo: 'Red wine',
    drinkTwoDetail: 'light, fresh, no fuss',
    storyEyebrow: 'Our story',
    storyTitle: 'The name is French.',
    storyEmphasis: 'The spirit is local.',
    storyBodyOne: 'Kevin brought more than 12 years of pizza and cooking from Paris to Lisbon. With Giselle, he created a neighbourhood place for regulars and long tables.',
    storyBodyTwo: 'Beside Mercado de Alvalade, we bring slow-fermented dough together with Italian and Portuguese ingredients.',
    directions: 'Find the way',
    storyQuote: 'A neighbourhood pizzeria, a community built around pizza.',
    visitEyebrow: 'Come visit us',
    visitTitle: 'Right beside',
    visitEmphasis: 'the Market.',
    visitLede: 'In the heart of the neighbourhood. Bring friends, an appetite and your four-legged companion — we are pet friendly.',
    hoursLabel: 'Opening hours',
    daysOne: 'Tuesday to Thursday',
    daysTwo: 'Friday and Saturday',
    daysClosed: 'Sunday and Monday',
    closed: 'closed',
    hoursNote: 'Tables are first come, first served. We are pet friendly.',
    location: 'Find us',
    openDirections: 'Open directions',
    socialEyebrow: 'From our table',
    socialTitle: 'See you on',
    socialEmphasis: 'Instagram.',
    viewMore: 'see more',
    socialQuote: 'Your heart is not made of stone.',
    socialQuoteSmall: 'It is mozzarella and melts easily.',
    footerTagline: 'A pizza bar with an Alvalade accent.',
    contact: 'Talk to us',
    comeBy: 'Come by',
    footerMade: 'made hungry in Lisbon',
    backTop: 'Back to top',
  },
} as const;
